# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import temp_pb2 as temp__pb2


class TransactorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendTemp = channel.unary_unary(
                '/transaction.Transactor/SendTemp',
                request_serializer=temp__pb2.TempEvent.SerializeToString,
                response_deserializer=temp__pb2.Void.FromString,
                )


class TransactorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendTemp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendTemp': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTemp,
                    request_deserializer=temp__pb2.TempEvent.FromString,
                    response_serializer=temp__pb2.Void.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transaction.Transactor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Transactor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendTemp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction.Transactor/SendTemp',
            temp__pb2.TempEvent.SerializeToString,
            temp__pb2.Void.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
