# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='temp.proto',
  package='transaction',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ntemp.proto\x12\x0btransaction\"e\n\tTempEvent\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\x05\x12\x0f\n\x07\x65ventId\x18\x02 \x01(\x05\x12\x10\n\x08humidity\x18\x03 \x01(\x02\x12\x0f\n\x07tempCel\x18\x04 \x01(\x02\x12\x12\n\nheatIdxCel\x18\x05 \x01(\x02\"\x06\n\x04Void2C\n\nTransactor\x12\x35\n\x08SendTemp\x12\x16.transaction.TempEvent\x1a\x11.transaction.Voidb\x06proto3'
)




_TEMPEVENT = _descriptor.Descriptor(
  name='TempEvent',
  full_name='transaction.TempEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceId', full_name='transaction.TempEvent.deviceId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eventId', full_name='transaction.TempEvent.eventId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='transaction.TempEvent.humidity', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tempCel', full_name='transaction.TempEvent.tempCel', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heatIdxCel', full_name='transaction.TempEvent.heatIdxCel', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=128,
)


_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='transaction.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['TempEvent'] = _TEMPEVENT
DESCRIPTOR.message_types_by_name['Void'] = _VOID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TempEvent = _reflection.GeneratedProtocolMessageType('TempEvent', (_message.Message,), {
  'DESCRIPTOR' : _TEMPEVENT,
  '__module__' : 'temp_pb2'
  # @@protoc_insertion_point(class_scope:transaction.TempEvent)
  })
_sym_db.RegisterMessage(TempEvent)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'temp_pb2'
  # @@protoc_insertion_point(class_scope:transaction.Void)
  })
_sym_db.RegisterMessage(Void)



_TRANSACTOR = _descriptor.ServiceDescriptor(
  name='Transactor',
  full_name='transaction.Transactor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=138,
  serialized_end=205,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendTemp',
    full_name='transaction.Transactor.SendTemp',
    index=0,
    containing_service=None,
    input_type=_TEMPEVENT,
    output_type=_VOID,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSACTOR)

DESCRIPTOR.services_by_name['Transactor'] = _TRANSACTOR

# @@protoc_insertion_point(module_scope)
